ALTER TABLE warga ADD COLUMN avatar_url VARCHAR(255) DEFAULT NULL;
ALTER TABLE rt ADD COLUMN avatar_url VARCHAR(255) DEFAULT NULL;
ALTER TABLE rw ADD COLUMN avatar_url VARCHAR(255) DEFAULT NULL;
ALTER TABLE superadmin ADD COLUMN avatar_url VARCHAR(255) DEFAULT NULL;
